### PR TITLE
Single registration

### PR DESCRIPTION
**Pull request by polly1075**

### CODE REVIEW

**Comment by autotelik** [comment]
Looks good. Only comment I can think of is should we prefer divs over tables for responsive ? (prototype anyway so probably irrelevant)

**Comment by polly1075** [comment]
Great thanks, it's OK the table is set up to be responsive.

Have a good weekend.

Polly

**Comment by autotelik** [comment]
ok cool.

so you don't want to start a Div vs Table flame war @ 5.30 pm on a Friday then !?

**Comment by polly1075** [comment]
C'mon on then 'grrrr' :)

**Comment by autotelik** [comment]
problem is I don't actually know much more than  - 'I thinks divs are better than tables'

the end.

Have a good weekend.too

**Pull request merged**
